# Generated by Django 4.0.2 on 2022-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_param', models.TextField(db_index=True, help_text='The query param to match on.', verbose_name='Query Param')),
                ('redirect_url', models.URLField(help_text='Where to redirect this query to.', verbose_name='Redirect Url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
