# Generated by Django 4.0.2 on 2022-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='query_param',
            field=models.CharField(db_index=True, help_text='The query param to match on.', max_length=200, verbose_name='Query Param'),
        ),
    ]
