# Generated by Django 3.2.12 on 2022-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_redirect_query_param"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="times_used",
            field=models.PositiveIntegerField(
                default=0, help_text="How many times this redirect has been used."
            ),
        ),
    ]
