# Generated by Django 3.2.12 on 2022-07-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_redirect_times_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='requires_authentication',
            field=models.BooleanField(default=False, help_text='Does this entry require auth to view?'),
        ),
    ]
