# Generated by Django 3.2.12 on 2023-04-27 05:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_redirect_requires_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='meta_color',
            field=colorfield.fields.ColorField(default='#808080', help_text='Color for the og:color tag', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='redirect',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Text for the og:description tag', null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Text for the og:title tag', max_length=55, null=True),
        ),
    ]
