# Generated by Django 4.2 on 2023-04-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_auto_20230427_0539"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="times_embedded_in_discord",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times discord has requested this URL for embedding on the platform.",
            ),
        ),
    ]
